---
- hosts: all
  become: true
  tasks:
  - name: Create Kubernetes namespace devops-tools
    become: false
    command: kubectl create namespace devops-tools
    when: ansible_swaptotal_mb > 0

  - name: Deploy devops-tools on Kubernetes cluster
    command: kubectl create -f deployment.yaml
    notify: kubectl get po -n devops-tools
    state: present




 #Setup a handler for checking Docker daemon using the below code.
  handlers:
    - name: docker status
      service: name=docker state=started