apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: devops-deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nexus-server
  template:
    metadata:
      labels:
        run: nexus-server
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "256m"
          ports:
            - containerPort: 8081
              protocol: TCP
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: nexus-data
          emptyDir: {}